ggave.mag/Higgs.Mbale.Web/Controllers/UsersAdminController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Higgs.Mbale.Web.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Threading.Tasks;
using Higgs.Mbale.EF.Models;
using System.Net;
using PagedList;
using Higgs.Mbale.BAL.Interface;

namespace Higgs.Mbale.Web.Controllers
{
    public class UsersAdminController : Controller
    {       MbaleEntities context = new MbaleEntities();
        private const int PAGESIZE = 500;
        private IUserService _userService;
        private IProductService _productService;
        private IBranchService _branchService;

        public UsersAdminController()
        {

        }

        public UsersAdminController(IUserService userService,IProductService productService,IBranchService branchService)
        {
            this._userService = userService;
            this._productService = productService;
            this._branchService = branchService;
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager, IUserService userService,IProductService productService,IBranchService branchService)
        {
            UserManager = userManager;
            RoleManager = roleManager;
            this._userService = userService;
            this._productService = productService;
            this._branchService = branchService;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }


        public ActionResult Index(string sortingOrder, string searchData, string Filter_Value, int? Page_No)
        {
            int Size_Of_Page = PAGESIZE;
            ViewBag.CurrentSortOrder = sortingOrder;
            ViewBag.SortingFirstName = String.IsNullOrEmpty(sortingOrder) ? "firstNameSorting" : "";
            ViewBag.SortingLastName = String.IsNullOrEmpty(sortingOrder) ? "lastNameSorting" : "";
            ViewBag.SortingUserName = String.IsNullOrEmpty(sortingOrder) ? "userNameSorting" : "";
            ViewBag.SortingPhoneNumber = String.IsNullOrEmpty(sortingOrder) ? "phoneNumberSorting" : "";
            ViewBag.SortingEmailAddress = String.IsNullOrEmpty(sortingOrder) ? "emailAddressSorting" : "";

            var searchText = string.Empty;
            if (!string.IsNullOrEmpty(searchData))
            {
                searchText = searchData.ToLower();
                Page_No = 1;
            }
            else
            {
                searchData = Filter_Value;
            }

            ViewBag.FilterValue = searchData;

            var usersx = UserManager.Users.ToList();
            var users = _userService.GetAllAdmins();
            if (users != null)
            {
                users = users.Where(u => u.FirstName.ToLower().Contains(searchText) ||
                u.LastName.ToLower().Contains(searchText)
                || u.Email.ToLower().Contains(searchText)
                || u.UserName.ToLower().Contains(searchText)).ToList();

            }

            switch (sortingOrder)
            {
                case "firstNameSorting":
                    users = users.OrderByDescending(u => u.FirstName).ToList();
                    break;
                case "lastNameSorting":
                    users = users.OrderByDescending(u => u.LastName).ToList();
                    break;
                case "userNameSorting":
                    users = users.OrderByDescending(u => u.UserName).ToList();
                    break;
                case "emailAddressSorting":
                    users = users.OrderByDescending(u => u.Email).ToList();
                    break;
                case "phoneNumberSorting":
                    users = users.OrderByDescending(u => u.PhoneNumber).ToList();
                    break;
                default:
                    users = users.OrderBy(u => u.FirstName).ToList(); ;
                    break;
            }


            int No_Of_Page = (Page_No ?? 1);
            return View(users.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        public ActionResult Suppliers(string sortingOrder, string searchData, string Filter_Value, int? Page_No, string submit = "")
        {
            int Size_Of_Page = PAGESIZE;
            ViewBag.CurrentSortOrder = sortingOrder;
            ViewBag.SortingFirstName = String.IsNullOrEmpty(sortingOrder) ? "firstNameSorting" : "";
            ViewBag.SortingLastName = String.IsNullOrEmpty(sortingOrder) ? "lastNameSorting" : "";
            ViewBag.SortingUserName = String.IsNullOrEmpty(sortingOrder) ? "userNameSorting" : "";
            ViewBag.SortingPhoneNumber = String.IsNullOrEmpty(sortingOrder) ? "phoneNumberSorting" : "";
            ViewBag.SortingEmailAddress = String.IsNullOrEmpty(sortingOrder) ? "emailAddressSorting" : "";

            var searchText = string.Empty;
            if (!string.IsNullOrEmpty(searchData))
            {
                searchText = searchData.ToLower();
                Page_No = 1;
            }
            else
            {
                searchData = Filter_Value;
            }

            ViewBag.FilterValue = searchData;

            var usersx = UserManager.Users.ToList();
            var users = _userService.GetAllSuppliers();
            if (users != null)
            {
                users = users.Where(u => u.FirstName.ToLower().Contains(searchText) ||
                u.LastName.ToLower().Contains(searchText)
                || u.Email.ToLower().Contains(searchText)
                || u.UserName.ToLower().Contains(searchText)).ToList();

            }

            switch (sortingOrder)
            {
                case "firstNameSorting":
                    users = users.OrderByDescending(u => u.FirstName).ToList();
                    break;
                case "lastNameSorting":
                    users = users.OrderByDescending(u => u.LastName).ToList();
                    break;
                case "userNameSorting":
                    users = users.OrderByDescending(u => u.UserName).ToList();
                    break;
                case "emailAddressSorting":
                    users = users.OrderByDescending(u => u.Email).ToList();
                    break;
                case "phoneNumberSorting":
                    users = users.OrderByDescending(u => u.PhoneNumber).ToList();
                    break;
                default:
                    users = users.OrderBy(u => u.FirstName).ToList(); ;
                    break;
            }


            int No_Of_Page = (Page_No ?? 1);
            return View(users.ToPagedList(No_Of_Page, Size_Of_Page));
        }

        public ActionResult Customers(string sortingOrder, string searchData, string Filter_Value, int? Page_No, string submit = "")
        {
            int Size_Of_Page = PAGESIZE;
            ViewBag.CurrentSortOrder = sortingOrder;
            ViewBag.SortingFirstName = String.IsNullOrEmpty(sortingOrder) ? "firstNameSorting" : "";
            ViewBag.SortingLastName = String.IsNullOrEmpty(sortingOrder) ? "lastNameSorting" : "";
            ViewBag.SortingUserName = String.IsNullOrEmpty(sortingOrder) ? "userNameSorting" : "";
            ViewBag.SortingPhoneNumber = String.IsNullOrEmpty(sortingOrder) ? "phoneNumberSorting" : "";
            ViewBag.SortingEmailAddress = String.IsNullOrEmpty(sortingOrder) ? "emailAddressSorting" : "";

            var searchText = string.Empty;
            if (!string.IsNullOrEmpty(searchData))
            {
                searchText = searchData.ToLower();
                Page_No = 1;
            }
            else
            {
                searchData = Filter_Value;
            }

            ViewBag.FilterValue = searchData;

            var usersx = UserManager.Users.ToList();
            var users = _userService.GetAllCustomers();
            if (users != null)
            {
                users = users.Where(u => u.FirstName.ToLower().Contains(searchText) ||
                u.LastName.ToLower().Contains(searchText)
                || u.Email.ToLower().Contains(searchText)
                || u.UserName.ToLower().Contains(searchText)).ToList();

            }

            switch (sortingOrder)
            {
                case "firstNameSorting":
                    users = users.OrderByDescending(u => u.FirstName).ToList();
                    break;
                case "lastNameSorting":
                    users = users.OrderByDescending(u => u.LastName).ToList();
                    break;
                case "userNameSorting":
                    users = users.OrderByDescending(u => u.UserName).ToList();
                    break;
                case "emailAddressSorting":
                    users = users.OrderByDescending(u => u.Email).ToList();
                    break;
                case "phoneNumberSorting":
                    users = users.OrderByDescending(u => u.PhoneNumber).ToList();
                    break;
                default:
                    users = users.OrderBy(u => u.FirstName).ToList(); ;
                    break;
            }


            int No_Of_Page = (Page_No ?? 1);
            return View(users.ToPagedList(No_Of_Page, Size_Of_Page));
        }

ggave.mag/Higgs.Mbale.Web/Views/UsersAdmin/Create.cshtml
@model  Higgs.Mbale.Web.Models.RegisterViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div id="header" ng-include="'/app/views/_common/header.html'"></div>


<aside id="menu"  ng-include="'/app/views/_common/navigation.html'"></aside>

<div id="wrapper">
@if (Request.IsAuthenticated && (User.IsInRole("superadmin") || User.IsInRole("supersuper")))
{
    <div class="content">
      
            <div id="page-title">
                <h4 class="page-header addon">Account - Create</h4>
            </div>

            <ol class="breadcrumb">
                <li><a href="/#/">Dashboard</a></li>
                <li>Account</li>
            </ol>

            <div class="clear0"></div>
            <hr />


            <div class="panel panel-default panel-left">
                <div class="panel-body">

                    @using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        <h4>Create a new account.</h4>
                        <hr />
                        @Html.ValidationSummary("", new { @class = "text-error" })
                        <div class="form-group">
                            @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.FirstName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.LastName, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.UniqueNumber, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.UniqueNumber, new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(m => m.Location, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Location, new { @class = "form-control" })
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(m => m.PhoneNumber, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                            </div>
                        </div>

                        @*<div class="form-group">
                            @Html.LabelFor(x => Model.SelectedRegionId, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-5">

                                </div>
            </div>*@

                        <!--<div class="form-group">
        @Html.LabelFor(m => m.RegionId, new { @class = "control-label col-md-2" })

        <!--<div class="col-md-10">-->
                        <!--@*@Html.DropDownList("Region", ViewData["DistrictsList"] as IEnumerable<SelectListItem>)*@-->
                        <!--@*@HtmlDropDownList("RegionId", (IEnumerable<SelectListItem>)ViewBag.Name, "Please Select ")*@-->
                        <!--@* @Html.DropDownList("Region", (SelectList)ViewBag.Name, "Please Select ")*@

        @* @Html.DropDownList("RegionId", (SelectList)ViewBag.Name, "Please Select ")*@-->

                        <!--</div>-->
                        <!--</div>-->
                        <div class="form-group">
                            @Html.LabelFor(m => m.RegionId, new { @class = "control-label col-md-2" })

                            <div class="col-md-10">

                                @Html.DropDownList("RegionId", (SelectList)ViewBag.Name, "Please Select ")

                            </div>
                        </div>

                        @*@Html.LabelFor(m => m.BranchId, new { @class = "control-label col-md-2" })*@

                       
                        <div class="form-group">
                            @Html.LabelFor(m => m.BranchId, new { @class = "control-label col-md-2" })

                            <div class="col-md-10">

                                @Html.DropDownList("BranchId", (SelectList)ViewBag.BranchName, "Please Select ")

                            </div>
                        </div>
                        @*<div class="form-group">
                <label class="col-md-2 control-label">
                    Select User Product
                </label>
                <div class="col-md-10">
                    @foreach (var item in (SelectList)ViewBag.ProductName)
                    {

                        <input type="checkbox" name="SelectedProducts" value="@item.Value" class="checkbox-inline" />
                        @Html.Label(item.Value, new { @class = "control-label" })

                    }
                </div>
            </div>*@
                        <div class="form-group">
                            @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                                <span style="color:#337ab7;">
                                    The Password must be at least 6 characters long, contain atleast one uppercase letter(A-Z),one lowercase letter(a-z),1 number(0-9),
                                    and one of the following characters:!@@#$%^&*()_+|~-=\{}[]:";<>?,./ Spaces are not allowed. for example AchBx$12_!
                                </span>
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                            <div class="col-md-10">
                                @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-md-2 control-label">
                                Select User Role
                            </label>
                            <div class="col-md-10">
                                @foreach (var item in (SelectList)ViewBag.RoleId)
                                {
                                    if (@item.Value == "superior")
                                    {
                                        <input type="hidden" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                        @Html.Label(item.Value, new { @class = "control-label" })
                                    }
                                    else
                                    {
                                        <input type="checkbox" name="SelectedRoles" value="@item.Value" class="checkbox-inline" />
                                        @Html.Label(item.Value, new { @class = "control-label" })

                                    }
                                }
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-offset-2 col-md-10">
                                <input type="submit" class="btn btn-default" value="Create" />
                            </div>
                        </div>
                    }

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
                    </div>
                    </div>
        }
                </div>

ggave.mag/Higgs.Mbale.Web/Views/UsersAdmin/Delete.cshtml
@model  Higgs.Mbale.Web.Models.ApplicationUser

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="header" ng-include="'/app/views/_common/header.html'"></div>


<aside id="menu"  ng-include="'/app/views/_common/navigation.html'"></aside>

<div id="wrapper">
@if (Request.IsAuthenticated && (User.IsInRole("admin") || User.IsInRole("superadmin")))
{
    <div class="content">
       

            <div id="page-title">
                <h1 class="page-header addon">Delete User</h1>
            </div>

            <ol class="breadcrumb">
                <li><a href="/#/">Dashboard</a></li>
                <li>Account</li>
            </ol>

            <div class="clear0"></div>
            <hr />


            <div class="panel panel-default panel-left">
                <div class="panel-body">

                    <h3>Are you sure you want to delete this User?</h3>
                    <div>
                        <table class="table table-bordered table-hover table-striped">
                            <tr>
                                <td width="50%">@Html.DisplayNameFor(model => model.FirstName)</td>
                                <td>@Html.DisplayFor(model => model.FirstName)</td>
                            </tr>
                            <tr>
                                <td width="50%">@Html.DisplayNameFor(model => model.LastName)</td>
                                <td>@Html.DisplayFor(model => model.LastName)</td>
                            </tr>
                            <tr>
                                <td width="50%">@Html.DisplayNameFor(model => model.Email)</td>
                                <td>@Html.DisplayFor(model => model.Email)</td>
                            </tr>
                            <tr>
                                <td width="50%">@Html.DisplayNameFor(model => model.PhoneNumber)</td>
                                <td>@Html.DisplayFor(model => model.PhoneNumber)</td>
                            </tr>
                        </table>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                </div>
            </div>
           
        </div>
}
    </div>

ggave.mag/Higgs.Mbale.Web/Views/UsersAdmin/Edit.cshtml
@model  Higgs.Mbale.Web.Models.AdminViewModels.EditUserViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="header" ng-include="'/app/views/_common/header.html'"></div>


<aside id="menu" ng-include="'/app/views/_common/navigation.html'"></aside>

<div id="wrapper">
@if (Request.IsAuthenticated && (User.IsInRole("admin") || User.IsInRole("superadmin")))
{
    <div class="content">
        
            <div id="page-title">
                <h4 class="page-header addon">Account - Edit</h4>
            </div>

            <ol class="breadcrumb">
                <li><a href="/#/">Dashboard</a></li>
                <li>Account</li>
            </ol>

            <div class="clear0"></div>
            <hr />


            <div class="panel panel-default panel-left">
                <div class="panel-body">

      
   
                    @using (Html.BeginForm("Edit", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            @Html.ValidationSummary("", new { @class = "text-error" })
                            @Html.HiddenFor(model => model.Id, new {@value= Model.Id  })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Email)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.UserName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.FirstName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.LastName)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.UniqueNumber, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.UniqueNumber, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.UniqueNumber)
                                </div>
                            </div>

                       
                            <div class="form-group">
                              
                           
                                @Html.LabelFor(x => Model.RegionId, htmlAttributes: new { @class = "control-label col-md-2" })
                              @*  @Html.DropDownListFor(x => Model.RegionId, (SelectList)ViewBag.Name, "Value", "Text")*@
                                @Html.DropDownList("RegionId", (SelectList)ViewBag.Name, "Please Select ")


                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.PhoneNumber)
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.Label("Roles", new { @class = "control-label col-md-2" })
                                <span class=" col-md-10">
                                    @if (Model.RolesList != null)
                                    {
                                        foreach (var item in Model.RolesList)
                                        {
                                            if (@item.Value == "superior")
                                            {
                                                <input type="hidden" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                                @Html.Label(item.Value, new { @class = "control-label" })
                                            }
                                            else
                                            {
                                                <input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                                                @Html.Label(item.Value, new { @class = "control-label" })

                                            }
                                        }
                                    }
                                </span>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Save" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>

                    @section Scripts {
                        @Scripts.Render("~/bundles/jqueryval")
                    }
                </div>
            </div>
    </div>
}
</div>